 #PostgreSQL. Versions 9.1 and up are supported.



default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-app-udemy_development


test:
  <<: *default
  database: rails-app-udemy_test


production:
  <<: *default
  database: rails-app-udemy_production
  username: troy
  password: <%= ENV['RAILS-APP-UDEMY_DATABASE_PASSWORD'] %>
#------------------------------------------------------------------------
#default: &default
#  adapter: postgresql
#  encoding: unicode
#  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 }.to_i %>
#  timeout: 5000
#  host: <%= ENV['DATA_DB_HOST'] %>
#  username: <%= ENV['DATA_DB_USER'] %>
#  password: <%= ENV['DATA_DB_PASS'] %>
#
#development:
#  <<: *default
#  database: hayman_development
#
#test:
#  <<: *default
#  database: hayman_test
#
#production:
#  <<: *default
#database: hayman_production
